name: deploy jar
on:
  workflow_dispatch:


permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: COPY file to Containerd
        uses: actions/checkout@v4 

      - name: set java version  
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Maven
        run: mvn clean package

      - name: Deploy to Server(京东云)
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PEM_KEY }}
          SOURCE: "target/xzs-3.9.0.jar"
          REMOTE_HOST: 116.196.80.124
          REMOTE_USER: root
          TARGET: /mnt/xzs-3.9.0.jar
          SCRIPT_AFTER: |
            pkill -f 'java -jar /mnt/xzs-3.9.0.jar'
            nohup /usr/local/java17/bin/java -Duser.timezone=Asia/Shanghai -jar -Dspring.profiles.active=prod  /mnt/xzs-3.9.0.jar  > /mnt/start1.log  2>&1 &
          

        
        # with:
        #   host: ${{ secrets.SERVER_ADDRESS }}
        #   username: ${{ secrets.SERVER_USER }}
        #   key: ${{ secrets.SSH_PEM_KEY }}
        #   script: |
        #     echo "ssh 连接成功"
        #     touch /root/action1.txt
